// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDY5WQXnhrzcCrEuTejME8JrYhEp9CLRo',
    appId: '1:919765150265:web:5830c8a886a888bdd7bbe8',
    messagingSenderId: '919765150265',
    projectId: 'virtual-wallet-8927f',
    authDomain: 'virtual-wallet-8927f.firebaseapp.com',
    storageBucket: 'virtual-wallet-8927f.appspot.com',
    measurementId: 'G-QTG8VCSCBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwNB_mekk4V6lX1gz4rMdvFkiWhVbDqsE',
    appId: '1:919765150265:android:51e72e045a8ac0cbd7bbe8',
    messagingSenderId: '919765150265',
    projectId: 'virtual-wallet-8927f',
    storageBucket: 'virtual-wallet-8927f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoVKMjCOgRCqNg7qpKtuaa3hmmcD9hOa8',
    appId: '1:919765150265:ios:4ea39bd3c6c29c19d7bbe8',
    messagingSenderId: '919765150265',
    projectId: 'virtual-wallet-8927f',
    storageBucket: 'virtual-wallet-8927f.appspot.com',
    iosBundleId: 'com.example.virtualWalletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoVKMjCOgRCqNg7qpKtuaa3hmmcD9hOa8',
    appId: '1:919765150265:ios:0db2ec2a066a02d0d7bbe8',
    messagingSenderId: '919765150265',
    projectId: 'virtual-wallet-8927f',
    storageBucket: 'virtual-wallet-8927f.appspot.com',
    iosBundleId: 'com.example.virtualWalletApp.RunnerTests',
  );
}
